language: php
php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_script:
  - composer install

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != "5.3" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ ; fi'
  - phpunit
