language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - sed -i '/ShortArraySyntaxSniff/d' vendor/internations/kodierungsregelwerksammlung/ruleset.xml
  - find vendor/internations/kodierungsregelwerksammlung/ -name "ShortArraySyntaxSniff.php" -exec rm {} \;

script:
  - phpunit

notifications:
  email:
    - lars.strojny@internations.org
    - max.beutel@internations.org
    - marc.jakubowski@internations.org
    - michael.weinrich@internations.org
    - vitor.balocco@internations.org
