language: php
php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_script:
  - composer install
  - sed -i '/ShortArraySyntaxSniff/d' vendor/internations/kodierungsregelwerksammlung/ruleset.xml
  - find vendor/internations/kodierungsregelwerksammlung/ -name "ShortArraySyntaxSniff.php" -exec rm {} \;

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != "5.3" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ ; fi'
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
